fix NPE
palantir/atlasdb pull request #6052
Opened 2022-05-20 16:11 UTC by gsheasby

**Goals (and why)**:
==COMMIT_MSG==
Fix NPE that can be encountered during restores.
==COMMIT_MSG==

**Implementation Description (bullets)**:

**Testing (What was existing testing like?  What have you done to improve it?)**:

**Concerns (what feedback would you like?)**:

**Where should we start reviewing?**:

**Priority (whenever / two weeks / yesterday)**:

2022-05-20 16:13 UTC, Jolyon-S approved these changes

2022-05-24 22:34 UTC, schlosna requested changes

2022-05-24 22:34 UTC, schlosna commented on atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/TokenRangeFetcher.java
> +            return null;
Do the callers handle null here (seems like `com.palantir.atlasdb.cassandra.backup.CassandraRepairHelper#getRangesToRepair` would now NPE constructing `RangesForRepair.of(null)`? 

Should this return an empty map or explicitly throw? I'm assuming we'd want the former based on how missing table metadata is handled below 

https://github.com/palantir/atlasdb/blob/f8febe4b86401b623a0b1d45769e0b686813bc09/atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/TokenRangeFetcher.java#L70-L75

```suggestion
            return ImmutableMap.of();
```

2022-05-24 22:36 UTC, schlosna commented on atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/CassandraRepairHelper.java
> +                    SafeArg.of("namespace", atlasService.getNamespace()),
[spotless wants a linebreak](https://app.circleci.com/pipelines/github/palantir/atlasdb/8594/workflows/c52f22f0-339a-47eb-b035-b8d491f74b04/jobs/33896)

```suggestion
            log.info(
                    "Repairing ranges for table",
                    SafeArg.of("namespace", atlasService.getNamespace()),
```


```
org.gradle.api.GradleException: The following files had format violations:
    src/main/java/com/palantir/atlasdb/cassandra/backup/CassandraRepairHelper.java
        @@ -121,7 +121,8 @@
         ················getRangesForRepairByTable(atlasService,·transactionsTableInteractions);
         
         ········tokenRangesForRepair.forEach((table,·ranges)·->·{
        -············log.info("Repairing·ranges·for·table",
        +············log.info(
        +····················"Repairing·ranges·for·table",
         ····················SafeArg.of("namespace",·atlasService.getNamespace()),
         ····················SafeArg.of("table",·table));
         ············repairTable.accept(table,·ranges);
Run './gradlew :atlasdb-cassandra:spotlessApply' to fix these violations.
```

2022-05-25 07:48 UTC, merged

2022-05-25 07:48 UTC, svc-autorelease commented
Released [0.615.0](https://github.com/palantir/atlasdb/releases/tag/0.615.0)