Immediately invalidate on lost leadership
palantir/atlasdb pull request #6828
Opened 2023-11-15 18:20 UTC by schlosna

Comments on #6824

2023-11-15 19:21 UTC, jeremyk-91 reviewed
I believe this makes sense, though as I'll be out for a bit, handing over to @LucasIME or @mdaudali to verify things are OK before merging

2023-11-15 19:21 UTC, jeremyk-91 commented on leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java
> +            Thread.currentThread().interrupt();
thanks for fixing this!

2023-11-27 16:00 UTC, mdaudali requested changes
Thanks for the change! I don't believe, in its current form, that it works as intended, but do correct me if I'm wrong

2023-11-27 16:00 UTC, mdaudali commented on leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java
> +                        return Futures.immediateFailedFuture(leadershipStateManager.invalidateStateOnLostLeadership(
I don't believe this is correct. Whilst the return type is the `NotCurrentLeaderException`, this method does not return the exception, but throws at evaluation. This means that instead of returning a future that fails, the handleInvocation method itself throws the exception, which is not what's intended here.

I wrote a mini test: 
```
    @Test
    public void areTheyTheSame() {
        Future<?> future = Futures.immediateFailedFuture(returnException());
        assertThat(future).isDone();
    }

    RuntimeException returnException() {
        return new RuntimeException("This is a test");
    }

    RuntimeException throwException() {
        throw new RuntimeException("This is a test");
    }
```

using returnException, the test passes. With throwException, the test fails as the method threw an exception, rather than the future failing

2023-11-27 16:00 UTC, mdaudali commented on leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java
> +                        return Futures.immediateFailedFuture(leadershipStateManager.invalidateStateOnLostLeadership(
I'll admit I'm a little surprised / concerned that none of our tests caught this.

2023-11-27 16:00 UTC, mdaudali commented on leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java
> +        } else if (cause instanceof ServiceNotAvailableException) {
Thanks! Would you mind leaving a comment + adding a test that covers this code path when thrown a NotCurrentLeaderException? Just want to make sure we don't regress if we change the parent type of the exception - and I couldn't see one where we had a test covering that...

2023-11-28 13:01 UTC, schlosna commented on leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java
> +                        return Futures.immediateFailedFuture(leadershipStateManager.invalidateStateOnLostLeadership(
good catch, will update and look into test coverage

2023-12-04 11:53 UTC, mdaudali approved these changes
Thanks! Left a couple comments that I hold as blocking approval - one to be actioned before merging, and the other optional in this PR.

2023-12-04 11:53 UTC, mdaudali commented on timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java
> +    private NotCurrentLeaderException notCurrentLeaderException(@CompileTimeConstant String message, Arg<?>... args) {
Any reason you chose to change the return type but not change the semantics to return the exception instead?

2023-12-04 11:53 UTC, mdaudali commented on leader-election-impl/src/test/java/com/palantir/leader/proxy/AwaitingLeadershipProxyTest.java
> +        Callable<Void> delegate = () -> {
Thanks for adding the tests! We're still not testing the case where we throw rather than returning a failed future (i.e., the mistake in the previous iteration), because the handleInvocation method unwraps the future anyway if the method under the proxy does not return a ListenableFuture. As a result, in the current test framework, the cases of throwing vs returning a failed future are not visibly different.

That said, from a review perspective, I'm happy with the change. If you want to go ahead with trying to get our tests to repro the above failure mode, please feel free and I can give it another review.

2023-12-04 14:46 UTC, mdaudali commented
We're about to revert the underlying PR for now, so holding off from merging this in. It will be relevant a little later

2024-05-22 16:47 UTC, mdaudali commented
@schlosna - revisiting this, would you be open to rebasing on top of develop so we can get this in?

2024-05-24 02:04 UTC, schlosna commented
> @schlosna - revisiting this, would you be open to rebasing on top of develop so we can get this in?

Yeah, I'll rebase and push in the morning.

2024-05-24 13:30 UTC, schlosna commented on timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java
> +    private NotCurrentLeaderException notCurrentLeaderException(@CompileTimeConstant String message, Arg<?>... args) {
I'm going to inline these two private methods (each only used once) as my main concern was someone in the future not throwing the returned exception.

2024-05-24 13:34 UTC, schlosna commented
Rebased and updated

2024-05-24 23:05 UTC, schlosna commented
Will wait to merge & release until Tuesday, May 28th to avoid anything rolling out over the long weekend.

2024-05-28 12:14 UTC, merged

2024-05-28 12:14 UTC, svc-autorelease commented
Released [0.1088.0](https://github.com/palantir/atlasdb/releases/tag/0.1088.0)